#!/bin/bash
apt-get update
apt-get install -y ca-certificates curl gnupg git
mkdir -p /etc/apt/keyrings
#install -m 0755 -d /etc/apt/keyrings
#curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
#chmod a+r /etc/apt/keyrings/docker.gpg
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
NODE_MAJOR=20
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
apt-get update
apt-get install nodejs -y
git clone https://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@github.com/shodanwashere/academy_travel
cd academy_travel
echo "PORT=3000" >> .env
echo "DB_CONNECTION_STRING=\"mongodb://40.113.66.133:27017/celfocusacademy?authSource=admin\"" >> .env
npm init -y
npm install express mongoose dotenv swagger-ui-express cors bcrypt
node index.js
# Add the repository to Apt sources:
#echo \
#  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
#  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
#  tee /etc/apt/sources.list.d/docker.list > /dev/null
#apt-get update
#apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#docker login harbor.cfappsecurity.com -u nuno.dias@celfocus.com -p QJid8qKr7
#docker pull harbor.cfappsecurity.com/travelr/travelr-backend:latest
#docker run -d -p 80:3000 harbor.cfappsecurity.com/travelr/travelr-backend:latest
